#
# Copyright (c) 2026 Ruben Perez Hidalgo (rubenperez038 at gmail dot com)
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#

version: 1.0.{build}-{branch}

shallow_clone: true

branches:
  only:
    - master
    - develop

image: Visual Studio 2019

environment:
  PATH: 'C:\Python314-x64;%PATH%'
  TOOLSET: msvc-14.2
  GENERATOR: Visual Studio 16 2019
  CXXSTD: 20
  BUILD_TYPE: Release
  BUILD_SHARED_LIBS: 1
  CXXFLAGS: /WX
      

install:
  - cmd: python tools\ci.py setup-boost --source-dir=%CD%
  - cmd: python tools\ci.py build-b2-distro --toolset %TOOLSET%

build_script:
  - cmd: >
      python tools\ci.py build-cmake-distro
      --build-type %BUILD_TYPE%
      --cxxstd %CXXSTD%
      --toolset %TOOLSET%
      --generator "%GENERATOR%"
      --build-shared-libs %BUILD_SHARED_LIBS%
      --integration-tests 0
      --cxxflags=%CXXFLAGS%
  - cmd: >
      python tools\ci.py run-cmake-add-subdirectory-tests
      --build-type %BUILD_TYPE%
      --cxxstd %CXXSTD%
      --toolset %TOOLSET%
      --generator "%GENERATOR%"
      --build-shared-libs %BUILD_SHARED_LIBS%
      --cxxflags=%CXXFLAGS%
  - cmd: >
      python tools\ci.py run-cmake-find-package-tests
      --build-type %BUILD_TYPE%
      --cxxstd %CXXSTD%
      --toolset %TOOLSET%
      --generator "%GENERATOR%"
      --build-shared-libs %BUILD_SHARED_LIBS%
      --cxxflags=%CXXFLAGS%
  - cmd: >
      python tools\ci.py run-cmake-b2-find-package-tests
      --build-type %BUILD_TYPE%
      --cxxstd %CXXSTD%
      --toolset %TOOLSET%
      --generator "%GENERATOR%"
      --build-shared-libs %BUILD_SHARED_LIBS%
      --cxxflags=%CXXFLAGS%

test: off
