if(NOT "${CONAN_FMT_ROOT}" STREQUAL "")
	set(fmt_FOUND TRUE)
	if(NOT TARGET fmt::fmt)
		add_library(fmt::fmt INTERFACE IMPORTED)
		target_link_libraries(fmt::fmt INTERFACE CONAN_PKG::fmt)
	endif()
else()
	set(fmt_FOUND FALSE)
endif()
