services:
  redis-master:
    image: ${SERVER_IMAGE}
    container_name: redis-master
    network_mode: host
    command:
      [
        "redis-server",
        "--replica-announce-ip", "localhost",
        "--protected-mode", "no",
        "--port", "6379",
        "--tls-port", "16379",
        "--tls-cert-file", "/docker/tls/server.crt",
        "--tls-key-file", "/docker/tls/server.key",
        "--tls-ca-cert-file", "/docker/tls/ca.crt",
        "--tls-auth-clients", "no",
      ]
    volumes:
      - ./docker:/docker


  redis-slave-1:
    image: ${SERVER_IMAGE}
    container_name: redis-slave-1
    depends_on:
      - redis-master
    network_mode: host
    command:
      [
        "redis-server",
        "--replica-announce-ip", "localhost",
        "--replicaof", "localhost", "6379",
        "--protected-mode", "no",
        "--port", "6380",
        "--tls-port", "16380",
        "--tls-cert-file", "/docker/tls/server.crt",
        "--tls-key-file", "/docker/tls/server.key",
        "--tls-ca-cert-file", "/docker/tls/ca.crt",
        "--tls-auth-clients", "no",
      ]
    volumes:
      - ./docker:/docker


  redis-slave-2:
    image: ${SERVER_IMAGE}
    container_name: redis-slave-2
    depends_on:
      - redis-master
    network_mode: host
    command:
      [
        "redis-server",
        "--replica-announce-ip", "localhost",
        "--replicaof", "localhost", "6379",
        "--protected-mode", "no",
        "--port", "6381",
        "--tls-port", "16381",
        "--tls-cert-file", "/docker/tls/server.crt",
        "--tls-key-file", "/docker/tls/server.key",
        "--tls-ca-cert-file", "/docker/tls/ca.crt",
        "--tls-auth-clients", "no",
      ]
    volumes:
      - ./docker:/docker


  sentinel-1:
    image: ${SERVER_IMAGE}
    container_name: sentinel-1
    network_mode: host
    command: >
      sh -c 'echo "port 26379" >> /etc/sentinel.conf &&
            echo "tls-port 36379" >> /etc/sentinel.conf &&
            echo "tls-cert-file /docker/tls/server.crt" >> /etc/sentinel.conf &&
            echo "tls-key-file /docker/tls/server.key" >> /etc/sentinel.conf &&
            echo "tls-ca-cert-file /docker/tls/ca.crt" >> /etc/sentinel.conf &&
            echo "tls-auth-clients no" >> /etc/sentinel.conf &&
            echo "tls-replication yes" >> /etc/sentinel.conf &&
            echo "sentinel monitor mymaster localhost 16379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel announce-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel announce-ip localhost" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds mymaster 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout mymaster 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs mymaster 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    volumes:
      - ./docker:/docker


  sentinel-2:
    image: ${SERVER_IMAGE}
    container_name: sentinel-2
    network_mode: host
    command: >
      sh -c 'echo "port 26380" >> /etc/sentinel.conf &&
            echo "tls-port 36380" >> /etc/sentinel.conf &&
            echo "tls-cert-file /docker/tls/server.crt" >> /etc/sentinel.conf &&
            echo "tls-key-file /docker/tls/server.key" >> /etc/sentinel.conf &&
            echo "tls-ca-cert-file /docker/tls/ca.crt" >> /etc/sentinel.conf &&
            echo "tls-auth-clients no" >> /etc/sentinel.conf &&
            echo "tls-replication yes" >> /etc/sentinel.conf &&
            echo "sentinel monitor mymaster localhost 16379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel announce-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel announce-ip localhost" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds mymaster 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout mymaster 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs mymaster 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    volumes:
      - ./docker:/docker

  sentinel-3:
    image: ${SERVER_IMAGE}
    container_name: sentinel-3
    network_mode: host
    command: >
      sh -c 'echo "port 26381" >> /etc/sentinel.conf &&
            echo "tls-port 36381" >> /etc/sentinel.conf &&
            echo "tls-cert-file /docker/tls/server.crt" >> /etc/sentinel.conf &&
            echo "tls-key-file /docker/tls/server.key" >> /etc/sentinel.conf &&
            echo "tls-ca-cert-file /docker/tls/ca.crt" >> /etc/sentinel.conf &&
            echo "tls-auth-clients no" >> /etc/sentinel.conf &&
            echo "tls-replication yes" >> /etc/sentinel.conf &&
            echo "sentinel monitor mymaster localhost 16379 2" >> /etc/sentinel.conf &&
            echo "sentinel resolve-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel announce-hostnames yes" >> /etc/sentinel.conf &&
            echo "sentinel announce-ip localhost" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds mymaster 10000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout mymaster 10000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs mymaster 1" >> /etc/sentinel.conf &&
            redis-sentinel /etc/sentinel.conf'
    volumes:
      - ./docker:/docker
